apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kargo-demo
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause:
          duration: 1m
      - setWeight: 30
      - pause:
          duration: 2m
      - setWeight: 60
      - pause:
          duration: 5m
      - setWeight: 100
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.27.3
        name: nginx
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 16Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: kargo-demo-content
        name: content
---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
spec:
  ports:
  - nodePort: 30083
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: kargo-demo
  type: NodePort
---
apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>prod</title>
    </head>
    <body>

    <h1>prod</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
