---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:prod
spec:
  project: default
  source:
    repoURL: https://github.com/luddskunk/kargo-demo
    targetRevision: stage/prod
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
