
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-harmony
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:harmony
spec:
  project: default
  source:
    repoURL: https://github.com/luddskunk/kargo-demo
    targetRevision: stage/harmony
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-harmony
  syncPolicy:
    syncOptions:
    - CreateNamespace=true