apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
  - stage: harmony
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/luddskunk/kargo-demo
  username: luddskunk
  password: <INPUT_SECRET>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.26.0
      discoveryLimit: 5
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: harmony
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/luddskunk/kargo-demo
          checkout:
          - branch: main
            path: ./src
          - branch: stage/harmony
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/stages/harmony
          images:
          - image: public.ecr.aws/nginx/nginx
      - uses: kustomize-build
        config:
          path: ./src/stages/harmony
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/harmony
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-harmony
            sources:
            - repoURL: https://github.com/luddskunk/kargo-demo
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - harmony
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/luddskunk/kargo-demo
          checkout:
          - branch: main
            path: ./src
          - branch: stage/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/stages/prod
          images:
          - image: public.ecr.aws/nginx/nginx
      - uses: kustomize-build
        config:
          path: ./src/stages/prod
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      # - uses: git-push
      #   as: push
      #   config:
      #     path: ./out
      #     generateTargetBranch: true
      # - uses: git-open-pr
      #   as: open-pr
      #   config:
      #     repoURL: ${GITOPS_REPO_URL}
      #     createTargetBranch: true
      #     sourceBranchFromStep: push
      #     targetBranch: stage/prod
      # - uses: git-wait-for-pr
      #   as: wait-for-pr
      #   config:
      #     repoURL: ${GITOPS_REPO_URL}
      #     prNumberFromStep: open-pr
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/prod
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-prod
            sources:
            - repoURL: https://github.com/luddskunk/kargo-demo
              desiredCommitFromStep: commit