apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo
spec:
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {duration: 1m}
      - setWeight: 30
      - pause: {duration: 2m}
      - setWeight: 60
      - pause: {duration: 5m}
      - setWeight: 100
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:placeholder
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
          readOnly: true
        resources:
          requests:
            memory: "16Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: content
        configMap:
          name: kargo-demo-content