apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/rollout.yaml
- ../../base/service.yaml
- configmap.yaml

patches:
- target:
    kind: Service
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30083
